# Generated by Django 3.1.4 on 2021-06-28 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('short_url', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('long_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.uniqueurl')),
            ],
        ),
    ]
