# Generated by Django 3.1.4 on 2021-06-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20210628_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorturl',
            name='long_url',
        ),
        migrations.AddField(
            model_name='uniqueurl',
            name='short_url',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app1.shorturl'),
            preserve_default=False,
        ),
    ]
