# Generated by Django 3.1.4 on 2021-06-28 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210628_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uniqueurl',
            name='short_url',
        ),
    ]
