# Generated by Django 3.2.4 on 2021-06-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_remove_uniqueurl_short_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UniqueUrl',
        ),
        migrations.AddField(
            model_name='shorturl',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
